SICRO = 'SC'
SINAPI = 'SN'
ANALITICO = 'AN'
SINTETICO = 'SI'
EQUIPAMENTO = 'EQ'
MAODEOBRA = 'MO'
MATERIAL = 'MA'
AUXILIAR = 'AT'
TEMPO_FIXO = 'TF'
TRANSPORTE = 'TR'
ONERADO = 'ON'
DESONERADO = 'DS'


ACRE = 'AC'
ALAGOAS = 'AL'
AMAPA = 'AP'
AMAZONAS = 'AM'
BAHIA = 'BA'
CEARA = 'CE'
DISTRITO_FEDERAL = 'DF'
ESPIRITO_SANTO = 'ES'
GOIAS = 'GO'
MARANHAO = 'MA'
MATO_GROSSO = 'MT'
MATO_GROSSO_DO_SUL = 'MS'
MINAS_GERAIS = 'MG'
PARA = 'PA'
PARAIBA = 'PB'
PARANA = 'PR'
PERNAMBUCO = 'PE'
PIAUI = 'PI'
RIO_DE_JANEIRO = 'RJ'
RIO_GRANDE_DO_NORTE = 'RN'
RIO_GRANDE_DO_SUL = 'RS'
RONDONIA = 'RO'
RORAIMA = 'RR'
SANTA_CATARINA = 'SC'
SAO_PAULO = 'SP'
SERGIPE = 'SE'
TOCANTINS = 'TO'

UF = [
(ACRE, 'AMAZONAS'),
(ALAGOAS, 'ALAGOAS'),
(AMAPA, 'AMAPÁ'),
(AMAZONAS, 'AMAZONAS'),
(BAHIA, 'BAHIA'),
(CEARA, 'CEARÁ'),
(DISTRITO_FEDERAL, 'DISTRITO FEDERAL'),
(ESPIRITO_SANTO, 'ESPÍRITO SANTO'),
(GOIAS, 'GOIÁS'),
(MARANHAO, 'MARANHÃO'),
(MATO_GROSSO, 'MATO GROSSO'),
(MATO_GROSSO_DO_SUL, 'MATO GROSSO DO SUL'),
(MINAS_GERAIS, 'MINAS GERAIS'),
(PARA, 'PARÁ'),
(PARAIBA, 'PARAÍBA'),
(PARANA, 'PARANÁ'),
(PERNAMBUCO, 'PERNAMBUCO'),
(PIAUI, 'PIAUÍ'),
(RIO_DE_JANEIRO, 'RIO DE JANEIRO'),
(RIO_GRANDE_DO_NORTE, 'RIO GRANDE DO NORTE'),
(RIO_GRANDE_DO_SUL, 'RIO GRANDE DO SUL'),
(RONDONIA, 'RONDÔNIA'),
(RORAIMA, 'RORAIMA'),
(SANTA_CATARINA, 'SANTA CATARINA'),
(SAO_PAULO, 'SÃO PAULO'),
(SERGIPE, 'SERGIPE'),
(TOCANTINS, 'TOCANTINS'),
]

FILE = [
(ANALITICO, 'ANALÍTICO'),
(SINTETICO, 'SINTÉTICO'),
(EQUIPAMENTO, 'EQUIPAMENTO'),
(MAODEOBRA, 'MÃO DE OBRA'),
(MATERIAL, 'MATERIAL'),
]

METHODOLOGY= [
(SICRO, 'SICRO'),
(SINAPI, 'SINAPI'),
]

TYPE_SYSTEM=[
(ONERADO, 'ONERADO'),
(DESONERADO, 'DESONERADO'),
]

INPUT_GROUP=[
(EQUIPAMENTO, 'EQUIPAMENTO'),
(MAODEOBRA, 'MÃO DE OBRA'),
(MATERIAL, 'MATERIAL'),
(AUXILIAR, 'ATIVIDADE AUXILIAR'),
(TEMPO_FIXO, 'TEMPO FIXO'),
(TRANSPORTE, 'TRANSPORTE'),
]

COMPOSITION_GROUP=[
('03', 'APARELHO DE APOIO'),
('04', 'ARMAÇÃO'),
('06', 'BUEIRO METÁLICO'),
('07', 'BUEIRO CELULAR'),
('08', 'BUEIRO TUBULAR'),
('09', 'INSTALAÇÕES INDUSTRIAIS'),
('11', 'CONCRETO'),
('12', 'CONCRETO PROJETADO'),
('14', 'CORTE'),
('15', 'CONTENÇÕES'),
('16', 'DEMOLIÇÃO'),
('17', 'DERROCAGEM'),
('18', 'LEVANTAMENTOS HIDROGRÁFICOS'),
('19', 'DRAGAGEM'),
('20', 'DRENAGEM'),
('21', 'ESCORAMENTO'),
('23', 'ESTACA'),
('24', 'ESTRUTURA METÁLICA'),
('26', 'FERROVIA-AMV'),
('28', 'FERROVIA-DEMOLIÇÃO'),
('29', 'FERROVIA-CORREÇÃO GEOMÉTRICA'),
('30', 'FERROVIA-GRADE'),
('31', 'FORMAS'),
('32', 'GABIÃO'),
('36', 'MOLHES'),
('37', 'OBRAS COMPLEMENTARES'),
('38', 'REFORÇO, ALARGAMENTO E MANUTENÇÃO DE OAE'),
('40', 'PAVIMENTAÇÃO RODOVIÁRIA'),
('42', 'PONTE ESTAIADA'),
('44', 'PROTEÇÃO AMBIENTAL'),
('45', 'PROTENSÃO'),
('48', 'SERVIÇOS AUXILIARES'),
('49', 'SERVIÇOS DE MANUTENÇÃO'),
('52', 'SINALIZAÇÃO'),
('53', 'SINALIZAÇÃO NÁUTICA'),
('54', 'SOLO REFORÇADO COM FITA'),
('55', 'TERRAPLENAGEM'),
('56', 'TIRANTES'),
('59', 'TRANSPORTE'),
('61', 'TUBULAÇÃO'),
('62', 'TÚNEL'),
('64', 'USINAGEM'),
('68', 'BUEIROS PRÉ-MOLDADOS'),
('71', 'IP4'),
]